// Generates a payroll-ready timesheet PDF for a date range, grouped by staff member.
// Mirrors the shape of generateAgreementPdf.js — build in-memory, return a Buffer.
const PDFDocument = require('pdfkit');

/**
 * @param {object} params
 * @param {Array} params.entries - rows from timesheet_entries joined with staff (first_name, last_name)
 * @param {string} params.start - ISO date string
 * @param {string} params.end - ISO date string
 * @returns {Promise<Buffer>}
 */
function generateTimesheetPdf({ entries, start, end }) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'LETTER', margin: 50 });
    const chunks = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const formatDate = (d) => new Date(d).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
    const formatTime = (d) => d ? new Date(d).toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' }) : '—';

    // Header
    doc.fontSize(20).fillColor('#0F5C5C').text('The Little Playhut', { align: 'center' });
    doc.moveDown(0.2);
    doc.fontSize(13).fillColor('#000000').text('Staff Timesheet Report', { align: 'center' });
    doc.fontSize(10).fillColor('#555555').text(`${formatDate(start)} – ${formatDate(end)}`, { align: 'center' });
    doc.moveDown(1.5);

    // Group entries by staff member
    const byStaff = {};
    for (const entry of entries) {
      const key = entry.staff_id;
      if (!byStaff[key]) {
        byStaff[key] = { name: `${entry.first_name} ${entry.last_name}`, entries: [], totalHours: 0 };
      }
      byStaff[key].entries.push(entry);
      byStaff[key].totalHours += Number(entry.total_hours) || 0;
    }

    const staffGroups = Object.values(byStaff);

    if (staffGroups.length === 0) {
      doc.fontSize(11).fillColor('#888888').text('No timesheet entries found for this date range.', { align: 'center' });
    }

    staffGroups.forEach((group, groupIndex) => {
      if (groupIndex > 0) doc.moveDown(1.2);

      doc.fontSize(13).fillColor('#0F5C5C').text(group.name);
      doc.moveDown(0.3);

      // Simple table header
      const startX = doc.x;
      doc.fontSize(9).fillColor('#555555');
      doc.text('Date', startX, doc.y, { continued: true, width: 100 });
      doc.text('Clock In', startX + 100, doc.y, { continued: true, width: 100 });
      doc.text('Clock Out', startX + 200, doc.y, { continued: true, width: 100 });
      doc.text('Hours', startX + 300, doc.y, { width: 80 });
      doc.moveDown(0.2);
      doc.moveTo(startX, doc.y).lineTo(startX + 400, doc.y).strokeColor('#D8CFC0').stroke();
      doc.moveDown(0.3);

      doc.fontSize(9.5).fillColor('#2B3333');
      group.entries
        .sort((a, b) => new Date(a.clock_in) - new Date(b.clock_in))
        .forEach((entry) => {
          const rowY = doc.y;
          doc.text(formatDate(entry.clock_in), startX, rowY, { continued: true, width: 100 });
          doc.text(formatTime(entry.clock_in), startX + 100, rowY, { continued: true, width: 100 });
          doc.text(formatTime(entry.clock_out), startX + 200, rowY, { continued: true, width: 100 });
          doc.text(entry.total_hours != null ? Number(entry.total_hours).toFixed(2) : '—', startX + 300, rowY, { width: 80 });
          doc.moveDown(0.35);
        });

      doc.moveDown(0.3);
      doc.fontSize(10.5).fillColor('#0F5C5C').text(`Total: ${group.totalHours.toFixed(2)} hours`, startX);
    });

    doc.moveDown(2);
    doc.fontSize(8).fillColor('#888888').text(
      'Generated by The Little Playhut staff dashboard.',
      { align: 'center' }
    );

    doc.end();
  });
}

module.exports = { generateTimesheetPdf };
