// Generates a simple signed-agreement PDF: title, signer name, timestamp, signature image.
// Mirrors the shape of KP's generateQuotePDF.js pattern — build in-memory, return a Buffer.
const PDFDocument = require('pdfkit');

/**
 * @param {object} params
 * @param {string} params.title - e.g. "Little Playhut Daycare Handbook Agreement"
 * @param {string} params.signerName
 * @param {string} params.signedAtISO - ISO timestamp string
 * @param {string} params.signatureDataUri - base64 data URI of the signature image (image/png)
 * @returns {Promise<Buffer>}
 */
function generateSignedAgreementPdf({ title, signerName, signedAtISO, signatureDataUri }) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'LETTER', margin: 50 });
    const chunks = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // Header
    doc.fontSize(20).fillColor('#1a2b4a').text('The Little Playhut', { align: 'center' });
    doc.moveDown(0.3);
    doc.fontSize(14).fillColor('#000000').text(title, { align: 'center' });
    doc.moveDown(1.5);

    // Body
    doc.fontSize(11).text(
      `This document certifies that ${signerName} has read, understood, and electronically agreed to the terms of the above handbook.`,
      { align: 'left' }
    );
    doc.moveDown(1);

    const signedDate = new Date(signedAtISO);
    doc.fontSize(11).text(`Signed by: ${signerName}`);
    doc.text(`Date: ${signedDate.toLocaleDateString('en-US')} at ${signedDate.toLocaleTimeString('en-US')}`);
    doc.moveDown(1);

    // Signature image, if provided as a base64 data URI
    if (signatureDataUri && signatureDataUri.startsWith('data:image')) {
      try {
        const base64Payload = signatureDataUri.split(',')[1];
        const imageBuffer = Buffer.from(base64Payload, 'base64');
        doc.text('Signature:', { continued: false });
        doc.moveDown(0.3);
        doc.image(imageBuffer, { fit: [300, 120] });
      } catch (err) {
        // If the signature image fails to decode, still produce the PDF without it
        // rather than failing the whole signing flow.
        doc.fontSize(9).fillColor('#888888').text('[Signature image could not be rendered]');
      }
    }

    doc.moveDown(2);
    doc.fontSize(8).fillColor('#888888').text(
      'This is an electronically signed document generated by The Little Playhut Preschool and Daycare.',
      { align: 'center' }
    );

    doc.end();
  });
}

module.exports = { generateSignedAgreementPdf };
